if 1
    execute 'source' fnamemodify(expand('<sfile>'), ':h').'/.vim/config/basic.vim'
    execute 'source' fnamemodify(expand('<sfile>'), ':h').'/.vim/config/plist.vim'
    execute 'source' fnamemodify(expand('<sfile>'), ':h').'/.vim/config/pconf.vim'
endif
